- Contents/Code/siteNewSensations.py
- Some models don't appear under /tour_ns/models/first-last or
/tour_ns/models/firstlast.
- For example Anya Olsen and Eliza Jane. Anya shows up at
/tour_ns/sets.php?id=2810 and Eliza at /tour_ns/sets.php?id=2811
- Allow search by id, which isn't ideal but otherwise the models
aren't findable with the other code.
> Handle NewSensations case where search by name fails

- Contents/Code/PAactors.py
- Contents/Code/PAsearchSites.py
- Contents/Code/__init__.py
- Contents/Code/addActors.py
- Contents/Code/siteMissaX.py
- Contents/Code/siteMylf.py
- README.md
- since Plex doesn't allow you to edit actors via its interface, created a workaround to manually set them
- mimics a separate site to fit within existing framework
- also sets date, scene name and studio name if you wish to pass them as well 
- to set actors, use fix match and search for:
- "add - actor name **and** actor name **and** actor name" (**and** can be replaced with a comma) **OR**
- "add **date** actor name **in** scene name **at** site name"
- created this for unsupported websites so I could at least set the actors easily
> Workaround to manually add actors + some new sites

- Contents/Code/siteNewSensations.py
Some older NewSensation actors have broken image links.
This causes an exception to cause the entire meta-data update to fail.
> Fix issue where getting actor image throws exception

- Contents/Code/siteNewSensations.py
The random actors who have sets.php produce an exception because the url isn't valid.
> Fix actors who have a sets.php url

- Contents/Code/PAsearchSites.py
- The processing on the search removes the dash from the name, and
it impossible to match CastingCouch-X, instead use castingcouchx.
> Fix CastingCouch-X to be searchable

- Contents/Code/siteNewSensations.py
This should help easier identification by user of matches
> Add release date to displayed NS search results

- README.md
- Fix formatting. For some reason, there were random commas in some places, '*' which I think was supposed to be used to make a list, etc.
- Remove XP as it is past EoL.
- Remove what appears to be duplicate linux entry (keep full path version)
- Change 'Mac OS' -> 'Mac'. 
- Change 'Windows 7/8' -> 'Windows'.
- Also fix Notice about Plex video files scanner, spaces were causing markdown not to parse.
I would like to consolidate the 'FreeNAS' entry, but paths both seemed unique, so I kept them. Not familiar with that OS or it's paths.
> Update Plex directory list

- docs/sitelist.md
SceneID is almost always found in URL, no need to state that again in the list for this item.
> Change SceneID section of fitting-room to standard format

- Contents/Code/siteFittingRoom.py
**Fitting-Room:**
- Create exceptions for several scenes that can't scrape collection info. Resolves #356.
> Fitting-Room Collection Bugfix

- Contents/Code/networkGammaEnt.py
The current amount of 90 pages results in too many occurrences. i.e., 1440 in girlways.
Usually happens, if the user searches for a complete enhanced title (Sitename - Actors - Title).
It results in searches that are too long and plex to time-out, returning as "no result." Meanwhile, the plug-in keeps indexing the results for 30 minutes or more.
A more conservative three pages might be enough for most searches returning 48 results. A brief check on most gamma sites has shown me that they are generous in the number of results per page.
> Reduce the amount of pages indexed

- Contents/Code/siteMylf.py
- Manual Scene Matching (Resolves #278)
- Remove code that downloads and analyzes artwork. Unnecessary (only one image available per scene) and resolves some issues with scraping images.
> Mylf Fixes

- Contents/Code/siteRealityLovers.py
* more reliable, some posters not found due to video and photo naming differences
* use actual poster url from search result instead of parsing one together
> reality lovers poster fix

- Contents/Code/networkBadoinkVR.py
String template `name="%s in [%s] % "` was missing a `s` but I also added the video title.
fixes:
`Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/networkBadoinkVR.py", line 27, in search
results.Append(MetadataSearchResult(id='%s|%d' % (curID, siteNum), name="%s in [%s] % " % (girlName, PAsearchSites.getSearchSiteName(siteNum), releaseDate), score=score, lang=lang))
ValueError: incomplete format`
> 18vr patch

- Contents/Code/PAactors.py
- Contents/Code/siteMilfVR.py
Fixed broken search and update function due to frontend updates.
Note: this is _mostly_ the same as the siteWankzvr.py with a few minor diffs. Maybe these could be combined in the future site->network?
Note: also added an alias to PAactors.py
`CRITICAL (agentkit:1018) - Exception in the search function of agent named 'PhoenixAdult', called with keyword arguments {'year': None, 'id': '17829', 'name': 'Milfvr on the Pole 180x180 3dh'} (most recent call last):
File "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-79e214ead/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1011, in _search
agent.search(*f_args, **f_kwargs)
File "/////Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 995, in search
results = …
> milfvr patch

- Contents/Code/PAsearchSites.py
- Contents/Code/__init__.py
- Contents/Code/siteDefeated.py
- Contents/Code/siteLustReality.py
- Contents/Code/siteSLR.py
- Contents/Code/siteXVirtual.py
- docs/sitelist.md
- Fixed the issues DirtyRacer mentioned at the previous pull request (except SearchDate,ReleaseDate thingy which i didn't understand)
- Added support for LustReality
- Added support for SexLikeReal
DefeatedXXX and DefeatedSexfight
Successfully recovers Title, Date, Description (short version), Rating, Label, Posters and Backgrounds for old and new videos of both sites. (Old videos used another format for posters/background).
The title of the video should be as follows:
SiteName - Title
SiteName - YYYY-MM-DD - Title
SiteName - Title - YYYY-MM-DD
For me all the above are working!
XVirtual
Successfully recovers Title, Description (long version), Genres, Label, Posters and Backgrounds for XVirtual site. Site doesn't provide date or model information. :(
The title of the video should be as …
> Added Support for DefeatedXXX, DefeatedSexFight, XVirtual, SexLikeReal, LustReality

- Contents/Code/PAsearchSites.py
- Contents/Code/__init__.py
- Contents/Code/siteRealJamVR.py
- Contents/Code/siteVRBangers.py
- Contents/Code/siteVRConk.py
- Contents/Code/siteVRPFilms.py
Added support for [http://vrconk.com](url) and [http://vrpfilms.com](url)
**VRConk search type: Exact Match - Direct URL (SiteName - Direct URL)**
Supports: Title, Summary, Release Date, Posters, Genres, Artwork, Actors
**RealJamVR search type: Exact Match - Direct URL (SiteName - Direct URL)**
Supports: Title, Summary, Release Date, Posters, Genres, Artwork, Actors
**VRP FIlms search type: Limited - Title Only**
Supports: Title, Summary (Partial), Release Date, Posters, Artwork, Actors
NOTE: Actor support may have issues with movies with more than one actor
Both sites work without error on multiple files, but I'm still learning xpath + python so apologies for any potential glitches, particularly with VRP Films.
> Added support for VRConk, RealJamVR, and VRP Films

- Contents/Code/networkKink.py
Using a media title SiteName - ID - Whatever wasn't working lately on all Kink subsites, however SiteName - Title was working.
Found out that the releaseDate parameter the old parse strftime is not exist as xpath anymore at Kink sites so I replaced it. Now it's working!
> networkKink Fix - Scene ID matching wasn't working

- Contents/Code/Update PAactors: Added Goldie Glock alias
On some sites Goldie Glock is simply named "Goldie" which messes up other movie libraries with the Actor and Musician [Goldie](https://www.themoviedb.org/person/1123329-goldie)
> Add Goldie Glock alias

- Contents/Code/networkGammaEntOther.py
Some scenes from EvilAngel have a pictures map entry which looks like this:
`u'': u'/9958/9958_03/previews/2/128/top_1_/9958_03_01.jpg'`
Since in this case the key is an empty string, a check is required to prevent an IndexError.
> fix EvilAngel poster fetching

- Contents/Code/networkGammaEntOther.py
This change fixes fetching of low res pictures for old EA scenes. The problem was that the keys in the pictures dict got sorted as a string. That means that the following set of keys looked like this when sorted descending:
'76x55',
'720x480',
'638x360',
'307x224',
'201x147',
'185x135'
This is why 76x55 'wins' as the best resolution while being the lowest. 
Fortunately the highest resoution picture is always stored in `['pictures']['nsfw']['top']['WIDTHxHEIGHT']`
Tested across all _GammaEntOther_ sites.
> fix low res picture for old EvilAngel scenes

- Contents/Code/siteHoloGirlsVR.py
- Contents/Code/siteSexLikeReal.py
- Contents/Code/siteVirtualReal.py
SexLikeReal videos used first the directURL to search list and because of different filename the URL wasn't valid. That crashed the agent. A simple try-except is enough so in case directURL is not valid then the GoogleSearch item will continue.
Added sceneID support for HoloGirlsVR. SiteName - sceneID - Whatever
Fixed VirtualRealPorn art download. They changed how gallery is so it would download only the poster. Fixed to download the gallery too.
> Minor Fix SexLikeReal, VirtualRealPorn - Added sceneID support for HoloGirlsVR

- Contents/Code/PAactors.py
- Contents/Code/PAsearchSites.py
- Contents/Code/__init__.py
- Contents/Code/siteAllAnalAllTheTime.py
- Contents/Code/siteMilfVR.py
- docs/sitelist.md
- metadate.studio typo at PAactors didn't return Actor metadata (Name,Photo) back to the plex (agent crashed). changed to metadata.studio
- SceneID support for WankzVR-MilfVR as i did with BaDoinkVR networks.
- Added support for AllAnalAllTheTime via sceneID. 
Title should be SiteName - SceneID - Whatever
Problem to find-collect the actorPhotoURL from this site. I got a lot of server didn't respond in time. Also they don't provide a link to actor Page (Join Now! redirect). Possibly can be collected via Models page. Choose the first letter of our model then redirect to the 'C' and then scrape through all of them and do name-string comparison.
> Fixed PAactors error,Added sceneID support for WankzVR-MilfVR,Added Support for AllAnalAllTheTime via sceneID

- Contents/Code/siteClips4Sale.py
First time contributor, lmk if there's a standardized process
Added a few actress names to the MEAN GIRLS/MEAN GIRLS POV studio.
There's a block of code (see below) that contains actress names only used in MEAN GIRLS POV but would not get tagged unless moved into the main MEAN GIRLS section. But it works fine now.
```python
if 'P-Jenn' in metadata.title:
movieActors.addActor('Empress Jennifer', '')
if 'Princess PERFECTION' in metadata.summary: 
movieActors.addActor('Princess Perfection', '')
if 'Goddess Farrah' in metadata.summary:
movieActors.addActor('Goddess Farrah', '')
if 'Goddess Alexis' in metadata.summary:
movieActors.addActor('Goddess Alexis', '')
if 'Goddess Nina' in metadata.summary:
movieActors.addActor('Goddess Nina', '')
if 'Goddess Randi' in metadata.summary: …
```
> Improve Actress Tagging for Clips4Sale (THE MEAN GIRLS POV studio)

- Contents/Code/PAsearchSites.py
- Contents/Code/site18OnlyGirls.py
- docs/sitelist.md
The current site for 18 Only Girls is rather limited in that the titles of Movies don't match what is listed on the site and the site is not up to date.
- Switching to "www.18onlygirlsblog.com" improves the chances of a match. 
- The new site also sometimes has image sets separate from the videos. 
- Description is not always available. 
- Actor image taken from old site "https://18onlygirls.tv/models/" if one exists, as the new site does not have actor images.
Enhanced Search Results:
- Suggest using Partial Title (full title does not always seem to work)
- Actor Name will also work
- Image Set results are filtered out to avoid duplicate results (the image set is grabbed with the video if it exists)
> Fix 18OnlyGirls - Move to New Source Site & Enhance Search

- Contents/Code/PAsearchSites.py
- Contents/Code/__init__.py
- Contents/Code/addActors.py
- Contents/Code/siteInTheCrack.py
- Contents/Code/siteSicflics.py
- docs/sitelist.md
Added support for sicflics.com:
> enhanced search
Improved addActors code:
> Code would split on every 'at' and on every 'in', it would also replace every 'and' in the scenetitle with ','
> So I did the following:
> 
> - only split on last 'at' so that any 'at' in the scenetitle will be kept;
> - only split on first 'in' so that any 'in' in the scenetitle will be kept;
> - split actors on 'and', not on ',' so that any 'and' in the scenetitle will be kept (no need to replace every 'and' with ',');
> - removed the .title() called on the sitename, so that formatting of the sitename will be kept: e.g. TestSite would be converted tot Testsite, which is not always the desired outcome.
> Added support for Sicflics site, improved addActors.py

- Contents/Code/PAutils.py
- Contents/Code/siteBangBros.py
This was specifically created for BangBros because of some of the terrible titles their site returns. The .title() function is severly limited and not tuned to handle specific scenarios. This can also be used for any site since it will take a properly formatted title and return it as is.
I have defined a utility that will handle most cases [that I ran into matching BangBros] where a title is not properly capitalized. 
This is kept in all cases. This is preferable because the capitalization provides emphasis and context.
Examples:
- "ASS"
-  "TITTIES"
This is kept in all cases. This is preferable because the capitalization provides emphasis and context.
Examples:
- "ASSets"
- "BangBros"
Remove spaces before punctuation 
Examples: 
- "ASS !" 
- "Help : I'm Stuck"
- "Hi.I can't put spaces …
> Suggestion: Title Case Parser

- Contents/Code/PAactors.py
- Contents/Code/siteDorcelClub.py
- Contents/Code/siteNewSensations.py
Fix for NewSensations site redesign as mentioned in issue #1101 
Some features removed from the site:
- No genres on scene pages, they only appear in dvds
- No link to dvds from scene pages
- No link to dvd cover from dvd page. (They still exist in [dvd list pages](https://www.newsensations.com/tour_ns/dvds/dvds.html), but I couldn't find a way to use it)
> Fix for NewSensations site redesign

- Contents/Code/siteMilfVR.py
* Fixes an index out of bounds error occuring in the update fn when no photo exists for the actor
* Example- `wankzvr-come-get-symz`
> WankzVR patch

- Contents/Code/PAsiteList.py
- Contents/Code/siteMelenaMariaRya.py
- docs/sitelist.md
- postprocessing2/PAsearchSites.py
The source site provides no artwork, no date info, rarely offers a description and has no search facility, so this system really only pulls the title and the occasional summary.
Matching must be done with scene ID, so an example search term of `melenamariarya 6700076` will return data from `melenamariarya.com/scene/6700076/hot-summer`
> Implements basic matching support for melenamariarya.com

- Contents/Code/networkStrike3.py
Fix genres tagging for new* scenes from Blacked, Vixen, Tushy...etc
I was not getting genres in the scenes after May-June 2020, seems they have changed the tags keywords.
> Fix NetworkStrike3 (Blacked, Vixen, Tushy, Deeper...) genre tagging for new scenes

- Contents/Code/PAdatabaseActors.py
- Contents/Code/PAsiteList.py
- Contents/Code/siteWatch4Beauty.py
- docs/sitelist.md
- postprocessing2/PAsearchSites.py
Allows rich content fetching with relatively robust searching considering that the site itself offers no scene search facility.
1. Attempt to use the searchTitle to match a model name and load the JSON list of scenes for that model
2. If no model name can be identified, attempt to load the JSON scene info for the searchTitle and if this succeeds, grab the model info and load the JSON list of scenes for that model
3. Loop through the available scenes, matching the date added if provided, or attempting to match against the remainder of the searchTitle
Example search strings to match `watch4beauty.com/updates/welcome-back`:
* `watch4beauty 2020 01 15 maria welcome back`
* `watch4beauty 2020 01 15 maria`
* `watch4beauty 2020 01 15 welcome back`
* `watch4beauty maria welcome back`
* …
> Implements support for Watch4Beauty

- Contents/Code/networkSteppedUp.py
Nympho changed their scene URL pattern. 
Old pattern was `view/id/title-of-scene`.
New pattern is `view/title-of-scene`.
However, matching old scenes by old pattern still works, so these changes enable both patterns to work.
> Fix nympho scene URL matching

- Contents/Code/PAactors.py
…kes sense to query indexxx.com first for model photos. Makes use of the new actor photo fetch/save/serve facility, which is renamed `cacheActorPhoto` to be more descriptive
> indexxx.com actorDBfinder and deploy actorSave/cacheActorPhoto

- Contents/Code/PAactors.py
This was a sneaky bug, as it would only appear in the event that the first actor DB site checked did **not** find a match, at which point it would return no result.
Example:
Custom order: YES
Order: `IAFD, Local Storage, Indexxx, Freeones, AdultDVDEmpire, Boobpedia, Babes and Stars, Babepedia`
Search for actor `Melena Maria Rya`
-- IAFD has no record for this actor, so we would expect to move on to local storage then Indexxx etc...
But we don't, because custom order would return only the first item because it in the example list, it was comparing `IAFD` with `IAFD ` (trailing space), resulting in no matching sourceName
> Fix multi-source actor matching

- Contents/Code/PAactors.py
- Contents/Code/siteJacquieEtMichel.py
IAFD matching would break if the actor was male, as it was only scanning #tblFem, while male results would sit in #tblMal - the xpath now includes both. Also added a facility to manually specify actors for Jacqie Et Michel TV with some examples.
> Fix IAFD matching and new actor facility for Jacqui Et Michel TV

- Contents/Code/siteData18Movies.py
Currently searching with Data18 can be a mess - tons of similar results and no way to really tell which is the one you want.
Changes will show Studio in brackets in search result to make matching a bit easier.
> Display studio when showing search results

- Contents/Code/siteData18Content.py
- Contents/Code/siteData18Movies.py
Data18 Movies have a breakdown of individual scenes in the movie. Many torrents come with these movies split into their original scenes.
Example: [Horny Housewives #1](http://www.data18.com/movies/1130883)
Check to see if there are any related scenes, and if so how many (Look at `Related Scenes [6]`)
Get each individual scene's link and add them to the search results in the format 
`Title [Scene X][studio] Date`
If the specific scene is chosen, the link (curID) for the entire movie will be replaced by the individual scene link in the `id` field
The ID field will have two new pieces of information added: original title (Horny Housewives #1)  and scene number (1).
In the `data18Movie`s update function, if the id field has more than 3 sections, the code will then switch to use the …
> Support for individual scenes

- Contents/Code/siteClips4Sale.py
The logic of the parts string handling had it logging "no scene name" if you included the Studio ID (userID) and a title. By changing the ==1 to !=1, it now appends the title to the search
> Fixed Clips4Sale search

- Contents/Code/networkStrike3.py
For `networkStrike3` sites, if searching by a video ID (i.e. most of these site's name their downloaded files `{site}_{id}_{resolution}.mp4`), use the `findOneVideo` graphql query instead of the `searchVideos` query.
> If searching by ID, use findOneVideo graphql query

- Contents/Code/PAsiteList.py
- Contents/Code/networkScoreGroup.py
Videos with id starting with 2 would try to match Scoreland2 instead of Scoreland
Use ScorelandTwo as a work around and add abbreviation Scoreland2
Add Christy Marks when matching that site
> Fix matching issue between Scoreland and Scoreland 2

- Contents/Code/PAsiteList.py
- docs/sitelist.md
Added FreeuseMILF, MomSwap, and PervDoctor.
Couldn't get metadata to pull when searching FreeuseMILF and MomSwap using siteMylf.py, but could get metadata when using networkTeamSkeet.py. Only issue with that is the studio for those two sites is then listed as TeamSkeet instead of Mylf.
> TeamSkeet/Mylf Additions

- Contents/Code/siteNewSensations.py
I think that NewSensations currently can't scrape using Enhanced - Date Add Search because it's not retrieving the right metadata. I tested this and I think it should close a few open issues as well.
https://github.com/PAhelper/PhoenixAdult.bundle/issues/1383
https://github.com/PAhelper/PhoenixAdult.bundle/issues/1349
> Fixing NewSensations site HTML scan update

- Contents/Code/networkGrooby.py
Attempts to Refresh Metadata on scenes from tgirls.porn appear crash due to `dateNode[0]` not having a `text_content()` attribute
_ElementStringResult has no attribute text_content
In function `search` in *networkGrooby.py*, the date is extracted from `dateNode[0]` without touching a `text_content()` attribute, so it's possible `search` was updated at some point previously to remove the call to `text_attribute()` and `update` was not updated.
In any case, to err on the side of caution with respect to other Grooby sites, this PR updates *networkGrooby.py* to access `dateNode[0].text_content()` only *if* the HTML that was returned from the xpath query contains such an attribute; otherwise, `dateNode[0]` is treated as being a string value already
> Fix tgirls.porn Crashing When Parsing Release Date

- Contents/Code/PAutils.py
- Contents/Code/siteAdultEmpire.py
- Contents/Code/siteData18Empire.py
- Contents/Code/siteData18Movies.py
- Contents/Code/siteData18Scenes.py
- Isolate Symbol code to reduce code redundancy
- Add plus, period and forward slash
- Prevent ellipses (...) from being removed
- Create any() function
- Address Several Exceptions in Search
- Don't Run Google Search if SceneID Provided
- Rework Scene Splitting
- Keep Track of Situations where scenes are duplicated
- Simplify XPaths
- If title has ", the" or ", a" move them to the front
-  Adjust actors to not fail
- Improve Search Results
- Improve Metadata
> Fix and Improve Data18/Adult Empire Search/Matching

- Contents/Code/networkPornWorld.py
Fix a few bits: date_object failed due to parse() being run on HTML elements rather than text, and the original title text replacement system needed attention
> Fix pornworld

- Contents/Code/siteClubFilly.py
Fixing the matching to ClubFilly, the old version wasn't picking up matches due to the `PAutils.Encode` not working
> Fix ClubFilly matching

- Contents/Code/PAactors.py
- Better Matching Instead of choosing First Result
- Collect Best Matches and Chooses Random Image if Multiple Matches (Refresh Metadate will rotate until happy)
- Look for Name is Aliases
- Look for Studio Name in Aliases for Site Based AKA
Example Anna Blaze pulls Brianna Blaze image (is fixed with this change)
Example Name in IAFD is Marie (tons of results)...Can keep refreshing until match is made
> Improve IAFD and Allow Refresh Metadata to Rotate Actor Images

- Contents/Code/__init__.py
When set as personal media's agent, the `media.name` and `media.filename` in the search function would be `None`. Get the media name from `primary_metadata`.
Users can set this agent above the Personal Media in the Agent menu, and get the landscape view from the web and apps.
Might help on solving https://github.com/PAhelper/PhoenixAdult.bundle/issues/1400
> Add use the agent in Personal Media (Other Videos)

- Contents/Code/siteData18Scenes.py
The actor photos require a referrer to retrieve from data18.com, so it's pointless to try and grab them as they will always fail and use a fallback actor image source.
#1547
> Remove Actor Photo URL to Prevent xpath Exception

- Contents/Code/siteXConfessions.py
```
2022-07-04 12:48:49,882 (7f8a38713b38) :  CRITICAL (agentkit:1095) - Exception in the update function of agent named 'PhoenixAdult', called with guid 'com.plexapp.agents.phoenixadult://hot-pot-3-way|695?lang=en' (most recent call last):
File "/usr/lib/plexmediaserver/Resources/Plug-ins-6b0e31a64/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1093, in _update
agent.update(obj, media, lang, **kwargs)
File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 142, in update
provider.update(metadata, lang, siteNum, movieGenres, movieActors, valid_images)
File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteXConfessions.py", line 92, …
```
> Fix possible undefined actor poster

- Contents/Code/PAsiteList.py
- Contents/Code/siteNaughtyAmerica.py
- docs/sitelist.md
Removed text check if scene ID used, since Algolia (https://i6p9q9r18e-3.algolianet.com/1/indexes/*/queries) link is dead making direct the only working search method.
Fixes #1587
> Naughty America: Fix Direct Search Date Error (No Longer Timestamp)

- Contents/Code/PAactors.py
- Contents/Code/PAdatabaseActors.py
Originally thought this was only going to be an issue with western names...apparently not. Moving to database to reduce clutter. 
Intention is to not use the English name from JavBus as it is not correct.
> Move JavBus Image Search Names to Database

- Contents/Code/PAdatabaseActors.py
- Contents/Code/PAsiteList.py
- Contents/Code/siteLittleCaprice.py
- docs/sitelist.md
Fixed LittleCaprice. 
This one is a bit weird. With the latest site change search results now link to the gallery page of the scene, which does not contain a lot of metadata, but it does contain pictures. There is a separate video page linked in the gallery page which does not contain a lot of images but has more relavant metadata (description, genres etc). The title and the date in these two pages can be slightly different. The search function will search and gather info from the gallery pages but the update function will use details from the video page (when avaliable).
Also added support for the sub-site names:
- Buttmuse
- Caprice Divas
- NasstyX
- POVDreams
- Streetfuck
- SuperprivateX
- Wecumtoyou
- Xpervo
> LittleCaprice changes

- Contents/Code/networkPornWorld.py
With most videos being released with titles in the format `Pornworld.23.03.16.Shalina.Devine...`, the current system does a terrible job at trying to get suitable matches, due to the equally terrible search system in use by the site. Instead, let's take that date info and use it against the 'Newest scenes' pages, where the most recent 99 scenes are on page 1 and all previous scenes are on subsequent pages. We'll try to make an intelligent guess for which page to scan, and jump to other pages as necessary until we find an approximate date match, then return results that are hopefully relevant. If we get a date match and the search title is a substring of the found result, that's a 100% match.
> Use date against 'Newest scenes' to get accurate scene matching

- Contents/Code/networkPornPros.py
Within the search function, the sceneURL is compared to directURL. If they are the same, then we replace plurals. ie. sisters become sister-s. This is problematic because we always turn sisters into sister-s even if the url is actually sisters. This makes the scene unsearchable.
Mitigate this case by searching both the plurals substituted and original sceneURL.
- Make a copy of searchResults called pluralResults
- Process the plurals, at the end append to pluralReults
- Remove duplicates from pluralResults and assign back to searchResults
> Improve plural variant handling

- Contents/Code/PAsiteList.py
- Contents/Code/networkHighTechVR.py
- postprocessing2/PAsearchSites.py
site updated
update page url
update xpath selectors
> sexbabevr patch

- Contents/Code/PAactors.py
- Contents/Code/PAdatabaseActors.py
- Contents/Code/PAutils.py
- Contents/Code/siteAdultEmpire.py
- Contents/Code/siteElegantAngel.py
Improve Gender Filter
General 
- Fix Elegant Angel Search #1823 and add Parse Title
- Fix Titles that are formatted for Sorting (sort title)
Adult Empire
- Add Directors
- Add Producers
- Get Background Images
- Add Result Type to Search Display [Movies, Videos, Blu-Ray, etc.]
- Fix Invalid Actors
> Fix Elegant Angel and Update Adult Empire

- Contents/Code/PAsiteList.py
- Contents/Code/PAutils.py
- Contents/Code/networkLoveHerFilms.py
- Contents/Code/networkTeamSkeet.py
- Contents/Code/siteATKGirlfriends.py
- Contents/Code/siteMomComesFirst.py
- Contents/Code/siteNewSensations.py
- Contents/Code/siteSpizoo.py
- docs/sitelist.md
NewSensations - Add Title Parser
TeamSkeet - Fix Variable Name
LoveHerFilms - Remove Hardcoded SiteName from Search
MomComesFirst - Add Actors to List
ATKGirlfriends - Add Renee Rose to SceneInfo Dict
Spizoo - Add MrLuckyRAW.com
Title Parser - Cleanup A.J., T.J., "(", LaSirena and "vs."
> Update Various Scrapers

- Contents/Code/siteXConfessions.py
- postprocessing2/PAsearchSites.py
Sometimes their search is misbehaving. I already handled this with their support multiple times, it ends up getting fixed, but it takes time and effort. In those cases, it helps trying to get the movie directly via its official slug. This is a good and clean work around imho.
- Filename: `XConfessions - private-dancer`
- Slug: `private-dancer`
```sh
curl -X POST 'https://api.xconfessions.com/api/search?query=a+man+of+faith'
| jq 'map(select(.resourceType == "movies").slug'
> ["man-faith"]
curl 'https://api.xconfessions.com/api/movies/slug/man-faith' | jq '.data.slug'
> "man-faith"
```
```sh
curl -X POST'https://api.xconfessions.com/api/search?query=private+dancer'
| jq 'map(select(.resourceType == "movies").slug'
> []
curl 'https://api.xconfessions.com/api/movies/slug/private-dancer' | jq …
```
> Improve XConfessions

- Contents/Code/PAutils.py
The current FlareSolverr version has a slightly different format for the headers which stopped it from working.
Resolves: https://github.com/PAhelper/PhoenixAdult.bundle/issues/1862
> FlareSolver FakeResponse Fix

- Contents/Code/PAsiteList.py
- Contents/Code/networkBellesa.py
- docs/sitelist.md
> Bellesa/Rework Bellesa to New Site

- Contents/Code/PAsiteList.py
- Contents/Code/networkKellyMadison.py
- Contents/Code/networkPornFidelity.py
- docs/sitelist.md
- Adds Date when Available
- Adds Actors from Search Results if no Public Page
- Correct Collections to Rely on filename if KM/TF not in title
- Improve Matches by Supporting URL ID and Episode ID (forms: e###, ###, or ##########)
- Backwards compatible with previous matches
- Rename to Kelly Madison Productions to match site
> KMP/Update KMadison/PFidelity/TFidelity to Handle Results with no Public Tour Page

- Contents/Code/network1service.py
Fixes #1911
Images are coming from API in the order: 1, 0, 2, 3, 4. Sorting them puts image 0 in front.
> N1S/Fix Image Order

- Contents/Code/networkRomero.py
- docs/sitelist.md
> BugFix/Fix Actors Not Showing in Defeated Sex Fight

- Contents/Code/siteXConfessions.py
Data response example
```json
{
"guest_stars": [],
"poster_picture": null,
"cover_title_picture": "https:\/\/img.lustcinema.com\/13a590d0-229b-4685-943e-325df91b35cd.jpeg?auto=compress%2Cformat",
"cover_title_animation": "https:\/\/img.lustcinema.com\/RmVMLoNuH4YRPfLwpdwohilCjUep3JJJXxjPTWjN.gif?auto=compress%2Cformat",
"info_title_picture": "https:\/\/img.lustcinema.com\/1a4977d1-572c-4243-8b42-c3c759405ebd.png?auto=compress%2Cformat",
"mobile_detail_picture": "https:\/\/img.lustcinema.com\/V2W5Ge49JJhi7alpvR4JQyjnMbH7jNDqn4LcvOFQ.jpeg?auto=compress%2Cformat",
"bts_poster_picture": "https:\/\/img.lustcinema.com\/PXaYaLdV6JQbxynMT84MqDafVvzPVSgf7xgRiny4.jpeg?auto=compress%2Cformat",
"banner_image": "https:\/\/img.lustcinema.com\/OvxKKXsqmH49JTMZJHU5OwqWhDeyRotNezpZOihg.jpeg?auto=compress%2 …
```
> fix(XConfessions): fallback if poster is None

- Contents/Code/siteXConfessions.py
Prevent error like those:
```python
Exception in the update function of agent named 'PhoenixAdult'
File "/usr/lib/plexmediaserver/Resources/Plug-ins-d301f511a/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1093, in _update
agent.update(obj, media, lang, **kwargs)
File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/__init__.py", line 161, in update
provider.update(metadata, lang, siteNum, movieGenres, movieActors, valid_images)
File "/config/Library/Application Support/Plex Media Server/Plug-ins/PhoenixAdult.bundle/Contents/Code/siteXConfessions.py", line 135, in update
art.append(detailsPageElements['banner_image_mobile'].split('?', 1)[0])
File …
```
> fix(XConfessions): fix compilation key
