Contents/Code/PAsearchSites.py, Contents/Code/__init__.py
- fixed index numbers for new Naughty America sites
- added new range of Naughty America sites to init.py 
- first time ive used a pull request so hopefully im doing this correctly
- @PAhelper thanks for your continuing support of this agent!
=> Added index numbers for new Naughty America Sites

Contents/Code/PAactors.py, Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkBadoinkVR.py, Contents/Code/siteSexBabesVR.py, Contents/Code/siteVRBangers.py, README.md
- VR Sites added didn't have internal search so these sites need to be searched with a Title search 
- (i.e. "VRBangers - Broken Heart.mp4")
- The only exception to this is SexBabesVR, which needs the Scene ID number as well, and needs the site title changed to "SexBVR" (to avoid detection as babes.com)
- (i.e. "SexBVR - 214 - Tied Beauty.mp4")
- Added two new NaughtyAmerica Sites (Watch Your Wife and Anal College)
=> Added some VR Sites and 2 new NaughtyAmerica Sites

Contents/Code/PAsearchSites.py, Contents/Code/networkPornPros.py
Fixes things like Stepsiblingscaught always matching to stepsiblings.
Fixes examples like PassionHD - Love and Lemonade matching to HD Love
Only works if your filename has the Site without spaces. i.e PassionHD not Passion HD.
No impact to existing code though. Just tries this method first.
=> Attempt to Fix incorrect site matches take 2

Contents/Code/networkPornPros.py
Summary fixes for multi paragraph spyfam sites.
Fix fansite matches when multiple actors found.
=> Pornpros improvements

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/siteNewSensations.py, Contents/Code/siteSexArt.py, Contents/Code/siteWankzVR.py, README.md
**Bugfixes**
- sexart/vivthomas/thelifeerotic fix for error when summaries not found
- wankzvr bugfix for new links on search page
- no longer need to use "SexBVR" instead of "SexBabesVR" because of your fix, updated name and readme to reflect this
- removed some extraneous logging
- added abbreviations
**New Sites**
- Baeb.com (pornpros), "Open Family" (NA)
=> Bugfixes, 2 new sites for existing networks

Contents/Code/PAextras.py, Contents/Code/networkPornPros.py, Contents/Code/siteSisLovesMe.py, Contents/Code/siteXart.py, postprocessing/windows/pa_renamer_post.py, postprocessing/windows/patools.py
Began consolidating fansite image searches into PAextras. Reduces code repetition in every site/network
Consolidated pornpros and Sisloves me so far.
Xart still has more work needed
Also uploading sabnzbd post processing script which as modified from @PAhelper2 to work with windows.
Still can use some improvements
=> Created PAextras for fansite searches

Contents/Code/PAactors.py, Contents/Code/networkDogfart.py
- Merged "Jo Jo Kiss" with "Jojo Kiss"
- Fixed Dogfart Network spelling error ("Dofgart Network" --> "Dogfart Network")
- Preliminary work on correcting X-Art actresses using [Indexxx.com](https://www.indexxx.com/websites/293/x-art/models2/) as a guide
=> Actress Corrections

Contents/Code/PAactors.py, Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkKink.py
-Support for Kink.com sub-site "Chantas Bitches"
-Comprehensive X-Art actress merge/overhaul (based on indexxx.com, verified with X-Art website).
=> Chantas Bitches/X-Art Actresses

Contents/Code/siteNewSensations.py
- Random actors on NewSensations will have a trailing dash, add a case for that.
=> Add case for when actor name url has trailing dash

Contents/Code/siteTonightsGirlfriend.py
* Processing of search string splits on the word `and` and anyone
with that in their name like Anderson, will have their name mangled.
=> Fix searching for Ashly Anderson

Contents/Code/__init__.py
fixes https://github.com/PAhelper/PhoenixAdult.bundle/issues/162
=> remove '4k' from search text

Contents/Code/siteBangBros.py, Contents/Code/siteRealityKings.py
=> Fix exceptions causing metadata to not return if url is bad

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkKink.py, Contents/Code/siteAllureMedia.py, Contents/Code/siteBangBros.py, Contents/Code/siteFemdomEmpire.py, Contents/Code/siteXart.py, README.md
- X-Art Scenes are now added to an X-Art Collection (Per #179)
- Punctuation is no longer stripped from X-Art Scene Titles
- Actresses can now be manually added to Amateur Allure Scenes (plugin searches Scene Title/Summary for matches)
- Femdom Empire support (everything but posters/artwork working) 
- README.md updated
- Fix Issue with Kink Network sites no longer pulling genres
- Fix Issue with BangBros release dates (per #182)
=> X-Art Fixes / Amateur Allure Actress Enhancements / Femdom Empire Support / Kink Network Fixes / BangBros Date Fix

Contents/Code/PAactors.py
Add renames to their official name
- Amy Reid -> Amy Ried
- Capri Cavalli -> Capri Cavanni
- Ce Ce Capella -> CeCe Capella
- Eve Lawrence -> Eve Laurence
- Nancy A. -> Nancy Ace
Add Stephanie Renee aliases
Add renames for DDFProd and RealityKings to more common name
=> Add names to remapping

Contents/Code/PAgenres.py, Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkDDFNetwork.py, Contents/Code/networkFemdomEmpire.py, Contents/Code/networkPornPros.py, Contents/Code/siteKarups.py, Contents/Code/siteTeamSkeet.py, Contents/Code/siteXConfessions.py
- TeamSkeet
- Skip attempt to pull actresses for scenes where actresses aren't listed
- Add actresses manually based on scene title
- Karups
- Skip attempt to pull scene artwork when it isn't available
- POVD
- Add actresses manually based on scene title
- DDFNetwork
- Support for pulling Summary for some older scenes
- Other
- More genre merges
- Feminized (Femdom Empire sister site) support
- XConfessions support (per @dismethis's request)
=> Genre Merges | Bugfixes | Actress Additions | Feminized Support | XConfessions Support

Contents/Code/PAgenres.py, Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkCzechAV.py, Contents/Code/siteArchAngel.py, Contents/Code/siteFamilyStrokes.py, Contents/Code/siteLoveHerFeet.py, Contents/Code/sitePrivate.py, Contents/Code/siteTemplate.py, Contents/Code/siteWeAreHairy.py, README.md
- Private
- Add to Collection using SearchSiteName when site code isn't available (per #207)
- FamilyStrokes
- Fix date format to reflect site code (when using fansite to match) (per #163) 
- ArchAngel
- Skip pulling summary when it is not available (per #209)
- Skip pulling video background (usually a lower quality version of the photos available)
- Updated code for pulling photos (so it works with more scenes)
- We Are Hairy Support
- Love Her Feet Support (per @insickin and @chempke's request)
- CzechAV Search Bugfix
- Update Template file
- Add genres based on number of actors
- Scrape summary
- Scrape directors
- Pull photos from gallery on scene page
- Other minor changes
- Several Genre Merges
=> Bugfixes | Update Template | Love Her Feet Support | We Are Hairy Support | Genre Merges

Contents/Code/PAactors.py, Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkFPN.py, Contents/Code/siteMomPOV.py, Contents/Code/sitePervMom.py, Contents/Code/siteTeamSkeet.py
- MomPOV
- Now Supported
- TeamSkeet
- Alternate Method of Pulling Actresses (resolves issues with scenes with multiple actresses)
- Other minor bugfixes
- PervMom
- Due to inconsistencies in code on scene pages, plug-in now pulls curID from SearchURL and searchTitle (fixes issue caused by 1b32c15 and resolves Issue #222)
- JamesDeen
- Manual Actor Addition for problematic scene (per Issue #127)
- Other Changes
- Actress Alias
=> MomPOV Support | Bugfixes

Contents/Code/siteXart.py
=> Xart bugfix

Contents/Code/networkNubiles.py
Some scenes don't have the pics button but some at least do have a poster set. This code grabs it if it can.
=> Added backup Poster code for scenes without Pics button

CHANGELOG.md, Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkNubiles.py, docs/sitelist.md
=> Add Nubiles ET and Detention Girls

CHANGELOG.md, Contents/Code/siteAllureMedia.py, Contents/Code/siteStepSecrets.py
**Amateur Media**
- Fix Search for Swallow Salon (Per #252)
- Update code to scrape cast photos
- More actress additions based on Scene Title/Summary
**StepSecrets**
- Title Bugfix (Per #256)
=> AmateurMedia Fixes/Improvements | StepSecrets Bugfix

Contents/Code/PAactors.py, Contents/Code/networkFemdomEmpire.py, Contents/Code/siteClips4Sale.py, Contents/Code/siteTeamSkeet.py
**Clips4Sale**
- More manual actor adds
**Femdom Empire**
- Manual scene adds (resolves some search shortcomings)
- Manual actor add
- Exception for when scene has no summary
**TeamSkeet**
- URL bugfix (resolves Issue #309 / #300) (thanks, @kamuk90!)
- Actor Bugfix (resolves Issue #307)
**Other**
- Actor Merges
=> Clips4Sale Improvements | Femdom Empire Improvements | Bugfixes

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/siteVogoV.py, docs/sitelist.md
Add VogoV.com (Aleksei Maetnyi (Markus Dupree) Co-Founder, Director & Male Performer)
I added logs for easy understanding the code @claygoldfinch
=> Add VogoV.com

Contents/Code/networkStrike3.py
**Strike3 Network**
- New method for scraping release date (as old method was broken)
- New method for scraping genres (as old method was broken)
- New method for scraping actor headshots (as old method was broken). Thanks to @kamuk90.
- New method for scraping director names (as old method was broken)
Resolves #346, #289, and #342
=> Strike3 Network Bugfixes

Contents/Code/networkBellaPass.py, Contents/Code/networkNubiles.py, Contents/Code/siteTwistys.py
**NubilesNetwork:**
- Summary Bugfix. Should resolve #357. If anyone with a large Nubiles Network library would like to test this out, that'd be greatly appreciated.
**Twistys**
- Search exception for an exceptionally problematic scene. Should resolve #337.
**BellaPass Network**
- Overhaul due to site change. Resolves #330.
=> NubilesNetwork, Twistys Bugfixes | BellaPass Overhaul

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, docs/sitelist.md
=> Add support for deeplush.com into nubiles network

Contents/Code/PAsearchSites.py, Contents/Code/networkDogfart.py, Contents/Code/networkSexyHub.py, Contents/Code/siteMomPOV.py, Contents/Code/siteNewSensations.py, docs/sitelist.md
**NewSensations:**
- Full conversion to DirectURL
- DVD releases now supported.
- DateAdd now supported for Scenes (previously no date was scraped)
- Should resolve #327, resolve #104, resolve #385
**MomPOV**
- Title Bugfix, resolves #405
**DogFart Network:**
- Cast code modernization, resolves #386
**SexyHub:**
- Exception for artwork
- Cast bugfix (Resolves #370)
=> NewSensations Overhaul, Bugfixes

Contents/Code/PAsearchSites.py, Contents/Code/networkGammaEnt.py, docs/sitelist.md
Might be something worth pulling in for now until someone can crack the code on matching with search.
=> Provide Limited Evil Angel suppot (directURL only)

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/sitePropertySex.py, docs/sitelist.md
**Twistys:**
- Subsite TurningTwistys now supported. Resolves #412.
PropertySex:
- Search Bugfix. Resolves #416.
=> TurningTwistys Support | PropertySex Bugfixes

Contents/Code/siteLoveHerFeet.py, Contents/Code/siteTemplate.py
**LoveHerFeet:**
- Overhaul due to site changes. Resolves #409.
**Misc:**
- Minor Template file updates.
=> LoveHerFeet Overhaul

Contents/Code/PAactors.py
Indenting was incorrect. Should be fixed with this pull.
=> Fixed issue with my previous change

Contents/Code/siteFittingRoom.py
=> FittingRoom Bugfix

Contents/Code/siteNewSensations.py
=> NewSensations Poster Fix

Contents/Code/siteSpizoo.py
Modernizes Spizoo/RawAttack and resolves #430
=> Spizoo Cleanup & Bugfix

Contents/Code/PAactors.py, Contents/Code/sitePervMom.py
- Fixed several issues with how PervMom handles actors
- Resolved #388 by removing code that attempted to download/analyze scraped poster
=> PervMom Bugfix

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkIntersec.py, Contents/Code/siteInsex.py, Contents/Code/siteJulesJordan.py, Contents/Code/siteTemplate.py, docs/sitelist.md
**Intersec Network:**
- Now supported
**Jules Jordan Network:**
- Modernized code
- GirlGirl now supported
**Misc:**
- Template updates
- Sitelist updates
=> Intersec Network Support | GirlGirl Support

Contents/Code/networkCherryPimps.py, docs/sitelist.md
**CherryPimps Network:**
- Improve matching
- Remove verbose logging
**Sitelist:**
- Update SisLovesMe with Date Add
=> CherryPimps Improvements | Update Sitelist

Contents/Code/networkPornPros.py, docs/sitelist.md
- Date bugfix (resolves #496 and #494)
- Date Add now supported
- Removed unused/unnecessary code 
- PassionHD scenes now have genre "Hardcore" added
=> PornPros Bugfix

Contents/Code/PAsearchSites.py
=> Add abbreviation(s)

Contents/Code/siteVRBangers.py
=> VRBangers Summary Bugfix

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkJapanese.py, Contents/Code/networkR18.py, docs/sitelist.md
Adding support japanese movies, by using r18.com
=> Japanese support

Contents/Code/siteAllureMedia.py
=> Fix 403 error

Contents/Code/sitePrivate.py
=> Search match fix

Contents/Code/PAgenres.py, Contents/Code/networkKink.py, Contents/Code/networkSteppedUp.py, Contents/Code/siteNaughtyAmerica.py, Contents/Code/siteTemplateSceneID.py, Contents/Code/siteTemplateSearch.py
NaughtyAmerica:
- Search bugfix
- Code modernization
Kink:
- ShootID now shown in search results
SteppedUpNetwork:
- Better automatic matching
- Code modernization
Other:
- Genre Merges
- Template updates
=> Bugfixes, Code Modernization, Minor Improvements

Contents/Code/PAsearchSites.py, Contents/Code/sitePlayboyPlus.py, docs/sitelist.md
=> PlayboyPlus fix

Contents/Code/networkKink.py
=> Kink search by scene id

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/siteJaysPOV.py, docs/sitelist.md
Found solution for #114
But i have problem with file matching, only `JAYsPOV` works correct, not `JAY's POV` or `JAYs POV`.
=> Adding support JAY's POV

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkGammaEnt.py, Contents/Code/siteGirlfriendsFilms.py, Contents/Code/siteVivid.py, docs/sitelist.md
Vivid Network:
- Now supported. Enhanced search using site API. Only individual scenes supported.
GirlfriendsFilms:
- Overhaul. SceneID only. Both DVDs and individual scenes supported. Please test @insickin and @pedrolara-boop. Resolves #347.
=> Vivid Support | GirlfriendsFilms Overhaul

Contents/Code/networkMetArt.py
=> Fix search and update

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkPureCFNM.py, docs/sitelist.md
PureCFNM Network:
- Now supported. ActressID with Title Search.
@jamesalexw figured it might be easier this way - you had a whole bunch of extra files in your PR that had been altered so I didn't want to merge it in as-is.  I played around with the search function a bit, as well. Test it out and let me know if you run into any issues!
=> PureCFNM Network Support

Contents/Code/PAsearchSites.py
=> Add site abbreviation

Contents/Code/siteVirtualReal.py
=> VirtualRealPorn fix

Contents/Code/networkMetArt.py
Fixes issue which @claygoldfinch mentioned in #568
=> MetArt fix

Contents/Code/__init__.py
=> DDF Network fix search and update

Contents/Code/siteBAMVisions.py
=> BAMVisions Fix

Contents/Code/networkGammaEnt.py
=> NuruMassage Search fix

Contents/Code/siteWowGirls.py
=> Wowgirls Fix

Contents/Code/network1service.py
Searching by ID for backward compatibility
=> Network1 search by ID

Contents/Code/PAsearchSites.py, Contents/Code/siteXConfessions.py
=> XConfessions API support

Contents/Code/network1service.py
=> Network1 trailers support

Contents/Code/networkStrike3.py
=> Fixed images

Contents/Code/PAsearchSites.py
=> Improved site search | Fixed empty sitelist on the second iteration

Contents/Code/sitePorndoePremium.py
=> LetsDoeIt Fix

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkPornPros.py
=> Added support BBC Pie

Contents/Code/siteGirlfriendsFilms.py
=> GirlfriendFilms Fix

Contents/Code/siteStepSecrets.py
=> Step Secrets Fix

Contents/Code/siteNaughtyAmerica.py
=> Naughty America Fix

Contents/Code/siteVRBangers.py
=> VRBangers Fix

Contents/Code/siteClips4Sale.py
Clips4Sale had stopped working, this seemed to fix it
=> clips4sale-search-fix

Contents/Code/__init__.py
Now it can take the site name from a sub-directory
=> Added support naming sites by directories

Contents/Code/__init__.py
=> Trying to fix filepath

CHANGELOG.md, Contents/Code/PAactors.py, Contents/Code/PAgenres.py, Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkGammaEnt.py, Contents/Code/networkPuffy.py, Contents/Code/networkSinX.py, Contents/Code/siteSinsLife.py, docs/sitelist.md
New Networks:
- Puffy Network (Wet and Pissy, Wet and Puffy, Simply Anal, Euro Babe Facials, We Like to Suck)
- SinX (Pissing in Action, Golden Shower Power, Fully Clothed Pissing)
- Other sites could easily be added, had no others to test
New sites:
- SinsLife
- Actor picture from site only works for one actor, not all Actors are listed on the site
- The previews on the search site have additional Pictures - may try to include these later
- Deviant Hardcore
- She Will Cheat
- Blowpass / My XXX Pass
Updated site:
- VIPissy
- Site changed, search works with title or actor
- Changed max Genre number to 150 after encountering a rare error on sites with >100 Tags
=> added Puffy Network + SinX + SinsLife + Deviant Hardcore + She Will Cheat + My XXX Pass + VIPissy fix

Contents/Code/networkStrike3.py
=> Strike 3 added bypass

Contents/Code/siteNaughtyAmerica.py
=> NaughtyAmerica increased search limit

Contents/Code/__init__.py
=> Lambda support

Contents/Code/PAutils.py, Contents/Code/siteWankzVR.py
=> WankzVR fixed search and update

Contents/Code/sitePorndoePremium.py
=> Fixed description

Contents/Code/PAsearchSites.py, Contents/Code/siteInterracialPass.py
=> InterracialPass fixed search and update

Contents/Code/siteGirlsRimming.py, docs/sitelist.md
=> Girlsrimming update

Contents/Code/networkGammaEntOther.py
=> Adder movie collection

Contents/Code/siteGirlsRimming.py
The typo PAUtils would crash the plugin on load.
Just changed to the correct PAutils
```
2020-05-06 15:40:12,586 (7f6d39e84700) :  INFO (core:349) - Starting framework core - Version: 2.6.3, Build: b69929d (Wed Apr 29 08:48:06 UTC 2020)
2020-05-06 15:40:12,587 (7f6d39e84700) :  DEBUG (core:361) - Using the elevated policy
2020-05-06 15:40:12,587 (7f6d39e84700) :  DEBUG (core:450) - Starting runtime component.
2020-05-06 15:40:12,590 (7f6d39e84700) :  DEBUG (core:450) - Starting caching component.
2020-05-06 15:40:12,591 (7f6d39e84700) :  DEBUG (core:450) - Starting data component.
2020-05-06 15:40:12,591 (7f6d39e84700) :  DEBUG (core:450) - Starting networking component.
2020-05-06 15:40:12,592 (7f6d39e84700) :  DEBUG (networking:261) - Loaded HTTP cookies
2020-05-06 15:40:12,592 …
```
=> Typo for PAutils

Contents/Code/siteGirlfriendsFilms.py
=> Girlfriendsfilms genres

Contents/Code/PAsearchSites.py, Contents/Code/siteJaysPOV.py
=> JaysPOV Fix

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, docs/sitelist.md
Added Anal Mom & Bellesa House to PASearchSites
=> Add AnalMom & BellesaHouse Support

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkR18.py, Contents/Code/siteRealityLovers.py
added siteRealityLovers.py
added rl to init.py
added rl to PAsearchSites.py
improved r18 search (better results returned when `-` replaced with whitespace)
=> Add RealityLovers site

Contents/Code/networkR18.py
fix whitespace in search
whitespace not getting converted to unicode (`%2B`)
=> r18 seach patch

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py
=> Added adulttime support

Contents/Code/networkBadoinkVR.py
Search fuction broken due to frontend updates
=> BadoinkVR patch

Contents/Code/siteDorcelClub.py
=> Fixed blurry images | Added gallery parsing

Contents/Code/networkIntersec.py
=> Updated search and update

Contents/Code/networkDDFNetwork.py
=> Added SceneID support

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkHighTechVR.py
added support for realjamvr to networkHighTechVR
=> Add RealJamVr Support

Contents/Code/siteNaughtyAmerica.py
=> Fixed actorsPageURL

Contents/Code/networkGammaEntOther.py
=> Replaced studio

Contents/Code/PAsearchSites.py
=> Improver sitename cleanup

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py
=> Fixed searchSiteID checking

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, docs/sitelist.md
=> Added more mylf sites

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, docs/sitelist.md
Support for Evolved Fights channels
Tested it for both channels and metadata comes to Plex with Success.
Filename had this format: SiteName - SceneID - Actors
=> Added Evolved Fights channels (Normal and Lesbian Edition) - Kink

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py
added wetvr support via pornprosnetwork
=> add wetvr support

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/siteHoloGirlsVR.py
added hologirlsvr support
created siteHoloGirlsVR (search based)
added hologirlsvr to init.py
added hologirlsvr to pssearchsites.py
=> hologirlsvr support

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/siteLethalHardcoreVR.py
added siteLethalHardcoreVR
added lethalhardcorevr to init.py
added lethalhardcorevr to pasearchsites.py
=> add support for lethalhardcorevr

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py
Added Gender X Support
Fixed Wicked.com to be under GammaOther
=> Added Gender X Support

Contents/Code/__init__.py
Removed extra OR operator on line 1341 which broke the plugin.
=> Update __init__.py - Bug Fix

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py
uses sitelethalhardcorevr.py
updated init and pasitesearch
=> add whorecraftvr support

Contents/Code/PAactors.py
=> Fixed recursion error

Contents/Code/networkFPN.py, Contents/Code/networkSteppedUp.py, Contents/Code/siteWicked.py
=> Improved NetworkFPN Search

Contents/Code/siteNaughtyAmerica.py
=> Fix Naughty America Actors and Genres

Contents/Code/PAactors.py
Reverts PAhelper/PhoenixAdult.bundle#869
=> Revert "Add Goldie Glock alias"

Contents/Code/siteLethalHardcoreVR.py
=> lethalhardcorevr patch

Contents/Code/siteAllureMedia.py
(metadata.summary) is always true
=> Fixed condition statement in siteAllureMedia.py

Contents/Code/networkBellaPass.py, Contents/Code/siteAllureMedia.py
I noticed that Swallow Salon still had errors. Then I checked which sites had the same error and fixed those too (which was BellaPass). Tested and working.
=> fix Swallow Salon and BellaPass

Contents/Code/networkGammaEntOther.py
This addition will always show female actors and then male actors for EvilAngel. I think this is a useful feature.
=> EvilAngel: show female actors first

Contents/Code/network1service.py, Contents/Code/networkBellaPass.py, Contents/Code/networkCherryPimps.py, Contents/Code/networkDDFNetwork.py, Contents/Code/networkGammaEntOther.py, Contents/Code/networkKink.py, Contents/Code/networkTeenMegaWorld.py, Contents/Code/siteMylf.py, Contents/Code/siteNaughtyAmerica.py
=> Minor Fixes

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, docs/sitelist.md
=> Added SapphiX Support

Contents/Code/__init__.py, Contents/DefaultPrefs.json
=> Added FileName Strip Option

Contents/Code/siteHucows.py
- Fixed XPath bug that caused titles to display as 'Join!' occasionally
- Added the SceneID to the search results for comparison (still can't search by sceneID though)
- 'HuCows' now gets added to Collections
=>  HuCows XPath bugfix and added sceneID to search results 

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py
Add Raw Couples - Teen Mega World
=> Add Raw Couples [TMW]

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/siteAussieAss.py, Contents/Code/siteBoxTruckSex.py, Contents/Code/siteScrewMeToo.py
New Sites:
- Box Truck Sex - Enhanced (Title/Actor/Date)
- ScrewMeToo - Enhanced (Title/Actor/Date)
- Aussie Ass - Enhanced (Actor/Title/SceneID/Date)
=> Add Aussie Ass, ScrewMeToo (FKA DateSlam) & BoxTruckSex Sites

Contents/Code/siteRealityLovers.py
update function broken
- malformed url
- img attribute incorrect
=> Reality Lovers VR Patch

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/network5Kporn.py, docs/sitelist.md
Add 5Kporn and 5Kteens
Update sitelist.md for 5Kporn and previously added sites
- Aussie Ass
- Box Truck Sex
- ScrewMeToo
=> New Network 5Kporn

Contents/Code/networkNubiles.py
=> Fixed Nubiles - Decoding Issue

Contents/Code/networkNubiles.py
=> Completely Removed Encode-Decode from Nubiles

Contents/Code/networkJavBus.py
JavBus:
- Fixed 'index out of range' error when search title could not be split
=> JavBus Search Bug Fix

Contents/Code/networkJavBus.py
Fixes bad URL when there are duplicate JAV IDs in the search results.
=> JavBus Search Fix

Contents/Code/siteFirstAnalQuest.py
=> bugfix: first anal quest update module

Contents/Code/__init__.py, Contents/Code/network1service.py
=> Add token saving

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py
=> added evilAngel subsite blackmailed

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkExploitedX.py, Contents/Code/siteDesperateAmateurs.py
Adding support for;
- ExploitedX network (Backroom Casting Couch,  Black Ambush, Exploited College Girls)
- Desperate Amateurs
=> Adding Support for ExploitedX network and DesperateAmateurs.com

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkDirtyHardDrive.py, Contents/Code/siteMeloneChallenge.py
Adding support for;
- Dirty Hard Drive Network (very old, but network is still up)
BangMyHand.com
DirtySlutsandStuds.com
KatieKox.com
SophieDeeAndFriends.com
LeeBangXXX.com
TheSquirtInstructor.com
GirlsInNylon.com
KieraKing.com
Example Filenames:
Bang My Hand - 2012-02-21 - Cum Guzzler.wmv
Katie Kox - 2012-02-21 - Can't Get Enough!.wmv
- Melone Challenge
Example Filenames:
Melone Challenge - 2017-08-29 - Mechanic with soft tools.mp4
Melone Challenge - 2017-08-01 - Great Fuck with No Cum.mp4
=> Adding 2 sites

Contents/Code/networkExploitedX.py, Contents/Code/networkPornPros.py, docs/sitelist.md
I had put one comment @DirtyRacer1337 where the site re-directs you to create an account if wrong DirectURL. req.ok didn't work because of this. I checked for a form element. If you have a better way to avoid this problem check it.
=> Pornpros Network - Added Support for Google Search

Contents/Code/networkExploitedX.py, usefulscripts/Plex-ActorSmartPlaylistGenerator/ActorSmartPlaylistGenerator.py, usefulscripts/Plex-ActorSmartPlaylistGenerator/requirements.txt
Added this script under usefulscripts/Plex-ActorSmartPlaylistGenerator for issue #1002 in case others want to do the same thing.
You will need to `pip install plexapi` and then edit the .py with your server and library info. Then the script will do the rest
=> Fixes ExploitedX - Added ActorSmartPlaylistGenerator script

Contents/Code/PAutils.py, Contents/Code/siteATKGirlfriends.py
=> Fix ATK | Minor changes

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py
Add Nubiles Sites:
GirlsOnlyPorn [NubilesFilms subsite]
FamilySwapXXX [New Nubiles-Porn subsite]
=> Add 2 Nubiles subsites

Contents/Code/__init__.py, Contents/Code/networkWankz.py, Contents/Code/siteRealityLovers.py
* corrected wankz search site
* corrected networkwankz.py xpaths
* corrected realitylovers url
=> Patch for Wankz and RealityLovers

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/siteAngelaWhite.py, Contents/Code/siteCumbizz.py, Contents/Code/siteHollyRandall.py, Contents/Code/siteInTheCrack.py, Contents/Code/sitePornstarPlatinum.py, Contents/Code/siteWoodmanCastingX.py, docs/sitelist.md
Hello
I added Holly Randall to the sitelist, I derived the code for the search and update functions from siteArchAngel.py as the websites are similar.
I added InTheCrack to the sitelist, I derived the code for the search and update functions from ATKGirlfriends.py as the websites are similar.
I can't test the code myself though
=> Added hollyrandall, inthecrack, angelawhite, cumbizz, pornstarplatinum, woordmancastingx

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkTeamSkeet.py, docs/sitelist.md
Switched several old TeamSkeet Network sites to use the main network site for searches. Added the newer TeamSkeet X Sites. Added some extra tagging for a few TeamSkeet sites.
=> TeamSkeet Patch

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/networkScoreGroup.py, docs/sitelist.md
Exact Matching Actor Name - SceneID
Example: https://www.pornmegaload.com/hd-porn-scenes/Paige-Turner/55346
Filename: PornMegaLoad - Paige Turner - 55346
Sites
- 18 Eighteen
- 50 Plus MILFS
- 60 Plus MILFS
- Big Boob Bundle
- Bootylicious Mag
- Leg Sex
- Naughty Mag
- Porn Mega Load
- Scoreland
- XL Girls
=> Add Network The Score Group

Contents/Code/PAsearchSites.py, Contents/Code/siteWoodmanCastingX.py
- Added WCX abbreviation
- Removed decoding from scene title
- Read actors from side panel list when available (continues to extract from the title if not available)
=> WoodmanCastingX improvements

Contents/Code/networkFullPornNetwork.py
Some scenes were failing due to scenePoster being None, added null check to avoid.
=> FullPornNetwork fix

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, Contents/Code/sitePorndoePremium.py, Contents/Code/siteTwoTGirls.py
I have added a new site TwoTGirls, feel free to test before merge, I have ran two full tests and both have pulled metadata no problem, filename used was: `<site-name> - <scene-date> - <scene-title>` title is required to get a match as I have based the search on the video pages instead of search results.
I'm not sure what to class it as, but for that fact I would say exact for now, maybe it falls into limited, but the date in filename does nothing apart from import into plex metadata, as they do not have the date on the site from what I can see.
If siteID needs changing, feel free, this was based on when I pulled the files
=> Add new site TwoTGirls

Contents/Code/PAactors.py
* added a handful of actor aliases based on duplicates in my collection
=> Add Actor Aliases

docs/manualsearch.md, docs/sitelist.md
Documented in manualsearch.md
Closes #1039
=> Documented the manual add if studio not supported

Contents/Code/siteCulioneros.py
Fix Bad Matches for Artwork and Resolve Int/String Error
Get Scene id from url and use to match when on actor page rather than scene title.
Fix
TypeError: cannot concatenate 'str' and 'int' objects
=> Culioneros Fixes

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, docs/sitelist.md
Glad to see ModelCentro added. Here is another site from their network. Added to paSearchSites, init, and site list.
=> Add Bruce and Morgan [ModelCentro]

Contents/Code/siteLethalHardcoreVR.py, Contents/Code/siteVRConk.py
Fix VRConk search for various scenes
Fix LethalHardcoreVR update for scene without descriptions
=> Patches for VRConk LethalHardcoreVR

Contents/Code/PAsearchSites.py, Contents/Code/__init__.py, docs/sitelist.md
Changed the sites previously associated with Pimp.XXX, renamed Family.XXX to Taboo (new name on CherryPimps), added Busted, Cheese.XXX, Femme, & Fresh
=> CherryPimps Updates

Contents/Code/siteXConfessions.py
Look for "movies" resourceType only.  "confessions" ressourceType may returns confessions only result.
=> Fix issue in search

Contents/Code/siteATKGirlfriends.py
Some results don't have a description. #1119
=> Fix ATK Girlfriends

Contents/Code/siteTonightsGirlfriend.py
updated search date and images url
=> fix Tonight's Girlfriend

Contents/Code/PAsiteList.py, docs/sitelist.md
Missed a markdown tag in the docs, and completely missed the site import 🤦🏻‍♂️
=> Fix errors in W4B

Contents/Code/__init__.py, Contents/Code/siteMelenaMariaRya.py
Improve some MelenaMariaRya metadata and log provider with `update` like we do with `search`
=> Misc improvements

Contents/Code/PAactors.py, Contents/Code/siteJoymii.py
…s most of the search terms from the web query, leaving only the first word. Most of the time, this will be the actor's first name, which results in good matches, which can then be fine-tuned with date matching and the LevenshteinDistance ranking system to get a perfect match. Also fixed a typo in PAactors.py
=> Improve Joymii matching

Contents/Code/siteAllAnalAllTheTime.py
Fixed sceneID for google search results + removing ' XXX' from the end of actor names
=> AllAnalAllTheTime: Fixed google search + delete XXX from end of actor names

Contents/Code/networkDDFNetwork.py
Added empty string in place of missing sceneCover value which broke update if matched by sceneID
=> DDF Scene ID search fix

Contents/Code/siteInterracialPass.py
=> Fixed studio for sites using InterracialPass provider

Contents/Code/PAsiteList.py, Contents/Code/networkDDFNetwork.py, Contents/Code/networkPornWorld.py, Contents/Code/networkTeamSkeet.py
=> HotLegsAndFeet Fix + netWorkPornWorld summary optional

Contents/Code/networkAdultEmpireCash.py
Adds new field for search result
MyPervyFamily - Date
FilthyKing networks (FilthyPOV, Massage, etc.) - Date and Specific network
=> Show date and network in search result

Contents/Code/__init__.py, Contents/DefaultPrefs.json, docs/manualsearch.md
Give your video a custom title using a combination of the following:
- Title
- Actors
- Series
- Studio
=> Add a way to give your videos a custom title

Contents/Code/networkAdultEmpireCash.py, Contents/Code/networkPornPros.py
AdultEmpireCash: Reverse studio and series fields
PornPros: Replace plurals with hyphenated word for url matching
=> Network consistency

Contents/Code/PAsiteList.py, Contents/Code/siteData18Empire.py, docs/sitelist.md
Support for site: https://data18.empirestores.co/
data18 is out of date and this is the new site.
=> New site: Data18Empire

Contents/Code/PAactors.py, Contents/Code/siteData18Empire.py
Some movies have >100 images in the gallery.
To prevent excessive downloading, this will randomly select 20 posters (vertical) and 5 artworks (horizontal) images
=> Minor changes Data18 Empire

Contents/Code/siteVRLatina.py
updated website broke scraper
update scraper
=> fix vrlatina

Contents/Code/PAsiteList.py, Contents/Code/siteTGirlJapan.py
tgirljapan and tgirljapanhardcore
=> Added tgirljapan

Contents/Code/PAsiteList.py, Contents/Code/siteAdultEmpire.py, Contents/Code/siteData18Empire.py, docs/sitelist.md
Support for [Adult Empire](https://www.adultempire.com/) (DVD site)
=> New site: Adult Empire

Contents/Code/siteAdultEmpire.py
=> Fix search url

Contents/Code/PAsiteList.py, Contents/Code/siteClips4Sale.py, Contents/Code/siteFamilyTherapy.py
New Site Family Therapy
Uses [FamilyTherapyxxx](https://familytherapyxxx.com/) to check for matches first
If no match is found, then check [Clips4Sale](https://www.clips4sale.com/studio/81593/family-therapy)
=> New Site: FamilyTherapy

Contents/Code/siteWowGirls.py
Currently only checks first page for matches
=> Update to check all pages

Contents/Code/network1service.py
Use both date and title to create score, not just one
=> Use date and title for score calculation

Contents/Code/networkMetadataAPI.py
Update how studio metadata is pulled
=> Pull site information to get parent netowrk name

Contents/Code/PAsearchSites.py, Contents/Code/PAsiteList.py, Contents/Code/networkModelCentro.py, Contents/Code/siteAlettaOceanLive.py
Updated modelcentro to work with AlettaOceanLive
=> Update to work with AlettaOcenLive

Contents/Code/networkNubiles.py
Gallery ID is not the same as video ID, so now it has to come from the "Pics" button. link has also changed from "src" to "srcset"
=> Update picture links

Contents/Code/PAsiteList.py, Contents/Code/siteFit18.py
Get matches from new site: **Fit 18**
Searches are done with just actor name and displays all options for that actor
=> Add site: Fit18

Contents/Code/PAsiteList.py
SpankMonster is now a part of AdultEmpireCash
=> Add site: SpankMonster

Contents/Code/PAsiteList.py, Contents/Code/networkGrooby.py, docs/sitelist.md
This includes changes to the Grooby file. I have made comments in the file about my changes to support more sites, please feel free to go through it and if you think work is needed just ping me and I will look into trying to make it work a little better. I am sure there can be changes to make this work better as my knowledge is limited, but in my testing this worked well for multiple sites from Grooby and I have updated the Site Doc to show this.
=> Changes to the Grooby Network File

Contents/Code/networkStrike3.py
Previously matched scene need to rematch to refresh metadata
=> networkStrike3: Switched to GraphQL requests, bypassed site change

Contents/Code/PAsiteList.py, Contents/Code/networkScoreGroup.py
Add support for christymarks.com
Fix other score sites
=> Fix ScoreGroup & Add christymarks.com

Contents/Code/PAsiteList.py, Contents/Code/networkScoreGroup.py, Contents/Code/siteData18Content.py, Contents/Code/siteData18Movies.py
Add Scoreland2
Query date for Data18 Movies & Content when not in metadata
=> Scoreland2 & Bugfix

Contents/Code/PAsiteList.py, Contents/Code/siteDarkRoomVR.py, docs/sitelist.md
Also having a comment out function to fetch more posters.
=> Added support for DarkRoomVR

Contents/Code/PAdatabaseActors.py, Contents/Code/sitePorndoePremium.py
Porndoe Premium searches were returning no results, this change should fix that
=> Fix PorndoePremium search

Contents/Code/PAdatabaseActors.py, Contents/Code/networkVNA.py, Contents/Code/siteAdultEmpire.py, Contents/Code/siteClips4Sale.py, Contents/Code/siteFinishesTheJob.py
Fix date error on Adult Empire
Better cleaning of titles in Clips4Sale
Updates to actors
=> Fix a variety of issues

Contents/Code/PAsiteList.py, Contents/Code/siteStasyq.py
Sadly incomplete metadata, but enough to match.
=> Add StasyQ (none vr version)

Contents/Code/PAsiteList.py, Contents/Code/siteBoundHoneys.py, Contents/Code/siteClips4Sale.py, Contents/Code/siteLustomic.py, Contents/Code/siteStraponCum.py, docs/sitelist.md
Sites Added: BoundHoneys, Girl Grind, Lustomic, Strapon Cum
Added actor matches for Clips4sale
Added new sites to sitelist and existing site that was missing (straplezz)
=> Added 4 new sites, updated sitelist, added actor match for clips4sale

Contents/Code/PAsiteList.py, Contents/Code/siteHotwifeXXX.py, docs/sitelist.md
My first contribution to this project.
I added the site HotwifeXXX and tested it. Search works through a google search and date matching like in the original NewSensations code.
Posters and actors are fetched properly.
=> add new site: HotwifeXXX

Contents/Code/networkAdultEmpireCash.py
Fix My Pervy Family 163a15a -> #1331 
Fix JAYs POV 32a26e1 -> #1342
=> Minor changes to AdultEmpireCash

Contents/Code/siteXart.py
Resolves #1062. Also adds additional custom search term mappings for titles with special characters or non-unique results.
=> Fixed X-Art poster retrieval

Contents/Code/PAsiteList.py
Waiting to get a few before opening to review. Currently:
- Family.XXX (familyxxx)
- TheRealWorkout (trwo)
- TeamSkeetXCamSoda (txc)
=> Add more site short terms

Contents/Code/PAactors.py, Contents/DefaultPrefs.json
Add ability to filter out male actors by using IAFD url.
Cases where a site specific photo url is passed will still be checked against IAFD for gender if option is enabled
=> New feature: Actor filter

Contents/Code/PAsiteList.py
added a new site from the Strike3 network
=> Add site: Slayed from network: Strike3

Contents/Code/PAsiteList.py, Contents/Code/siteFit18.py
Fixes Fit18 which was not working (images still fail to load)
=> Fit18 fixes

Contents/Code/networkAdultEmpireCash.py
Fixes SpankMonster failed matching
https://github.com/PAhelper/PhoenixAdult.bundle/issues/1356
https://github.com/PAhelper/PhoenixAdult.bundle/issues/1358
=> SpankMonster Fix

Contents/Code/networkNubiles.py
Fixes HotCrazyMess failing to load actor data due to having no image gallery
https://github.com/PAhelper/PhoenixAdult.bundle/issues/1378
=> HotCrazyMess Fix

Contents/Code/PAsiteList.py, Contents/Code/siteXSinsVR.py
* found search, no need for directUrl
* update gallary images
=> sinsvr2 patch

Contents/Code/networkModelCentro.py
Don't need to decode scene id anymore.
=> ModelCentro Matching Fix

Contents/Code/__init__.py
added this stash contribute line so phoenix can give the stash agent metadata if needed while allowing the stash agent to match with the local stash server perfectly.
=> added stash metadata agent contrib entry

Contents/Code/PAsiteList.py
Add BrattyMILF to Nubiles network
=> Add BrattyMILF

Contents/Code/PAdatabaseActors.py
=> Add Lacey Channing to actordb

Contents/Code/PAsiteList.py, Contents/Code/networkJavBus.py, Contents/Code/siteSwallowBay.py, docs/sitelist.md
* added swallowbay scraper
* exact match because site search returns links to galleries
=> swallowbay

Contents/Code/PAsiteList.py, docs/sitelist.md
Added I Made Porn & Sis Swap from TeamSkeet as well as Facials4k from Porn Pros.
=> Team skeet & porn pros

Contents/Code/sitePlumperPass.py
=> Update Plumper Pass XPaths to Match New Site Design

Contents/Code/PAsiteList.py, Contents/Code/siteData18Scenes.py
~This does not fix image collection. The images are no longer easily parsed. Trying to identify a pattern but currently having 0 luck.~
#1436
=> Data18 Scene Site Changes

Contents/Code/siteData18Scenes.py
Doing manual correction since Google has not updated to the URL change.
=> Fix Data18 Scenes Google Search and Minor Scraping Issues

Contents/Code/sitePOVR.py
updated score so that povr originals are matched correctly
=> povr patch

Contents/Code/siteVirtualTaboo.py
=> virtualtaboo

Contents/Code/PAsiteList.py, Contents/Code/siteVirtualPorn.py, docs/sitelist.md
added site for virtualporn (bangbros subsite but does not exist in their network atm)
=> add site virtualporn

Contents/Code/PAsiteList.py, Contents/Code/siteVRBangers.py, Contents/Code/siteVRConk.py
use new api
fix summary html issue in vrbangers (same api model as vrconk)
remove duplicate realjamvr entry from sitelist
=> fix vrconk scraper

Contents/Code/siteVRBangers.py, Contents/Code/siteVRConk.py
found rare bug where update fails if art work is missing
=> patch vrbangers vrconk

Contents/Code/networkHighTechVR.py
pulled out xpaths into site dict to make site changes easier to maintain
updated paths for realjamvr
=> fix hightechvr - realjamvr

Contents/Code/networkModelCentro.py
? in title causing plex guid parser to fail since it wasn't encoded
Also allow scene id to be used for 100% match
=> ModelCentro Cannot Update Metadata

Contents/Code/PAsiteList.py, Contents/Code/siteJavLibrary.py, docs/sitelist.md
added javlibrary as additional scraper
=> add javlibrary

Contents/Code/siteNaughtyAmerica.py
=> Fix Naughty America Search and Parse Titles

Contents/Code/networkNubiles.py
=> Nubiles Fix for Scenes Without a Gallery

Contents/Code/PAsiteList.py, Contents/Code/siteData18Scenes.py, docs/sitelist.md
Separating this because some Scenes are tied to movies, but that may not be the desired default image.
=> Data18 Grab DVD Covers for Movie Scenes

Contents/Code/PAsiteList.py, Contents/Code/PAutils.py, Contents/Code/networkHugeMedia.py, docs/sitelist.md
- Daddy4k
- Hunt4k
- Old4k
- Sis.Porn
- Stuck4k
- Tutor4k
=> Add Network Huge Media

Contents/Code/PAsiteList.py, Contents/Code/networkHugeMedia.py, docs/sitelist.md
- Black4k
- Mature4k
- Shame4k
- Rim4k
- Fist4k
=> Add Additional Sites to Huge Media

Contents/Code/PAsiteList.py, Contents/Code/networkSteppedUp.py
Other sites in the same network haven't change yet. Don't know if/when that'll happen.
=> TrueAnal site change

Contents/Code/networkAdultEmpireCash.py
quick fix for matching on jayspov and spankmonster
=> jayspov / spankmonster matching fix

Contents/Code/PAsiteList.py, docs/sitelist.md
Add teamskeet's new tinysis site to the list
=> Add Tiny Sis

Contents/Code/PAsiteList.py
Fixes FantasyMassage to use the same setup as AdultTime as it appears their websites have merged
=> Fix to FantasyMassage

Contents/Code/PAsiteList.py, Contents/Code/networkGrooby.py, docs/sitelist.md
Adding two new sites and fixing Gender X, they changed their site from genderx.com to genderxfilms.com
=> Add two Grooby sites and fix Gender X

Contents/Code/siteData18Movies.py, Contents/Code/siteData18Scenes.py
=> Data18 Update Actor Photo URL XPath

Contents/Code/networkFullPornNetwork.py
2 URL Cases Covered, may be more
FirstLast.html or first-last-followed-by-title.html
Examples:
https://baddaddypov.com/models/LaneyGrey.html
https://baddaddypov.com/models/alison-rey-teen-slut-with-small-tits-and-anatural-ass.html
=> FPN Add Direct URL for Model Page if Google Fails

Contents/Code/PAsiteList.py
Fixes PAhelper/PhoenixAdult.bundle#1402
=> Fix MyPervyFamily

Contents/Code/PAsiteList.py, docs/sitelist.md
Added mulitple Mylf X and TeamSkeet X sites as well as new sites from respective networks, added TMWPOV to TeenMegaWorld network, added Younger Mommy and Cum Swapping Sis to Nubiles network.
=> Add Mylf, TeamSkeet, Nubiles, TMW Sites

Contents/Code/PAactors.py
=> IAFD Operator -= is Not Supported

Contents/Code/siteData18Scenes.py
=> Fix Data18 Actors

Contents/Code/PAsiteList.py
Old search url wasn't working.
=> Fix ExCoGi

Contents/Code/networkAdultEmpireCash.py
adds missing actors for two spankmonster scenes
=> spankmonster missing actors

Contents/Code/PAsiteList.py
=> Fix backroomcastingcouch search url

Contents/Code/siteData18Scenes.py
change referrer for image pull from www.data18.com to i.dt18.com so images will work again.
=> Change Referrer for Image Pull

Contents/Code/PAdatabaseActors.py, Contents/Code/PAsiteList.py
Also add Gianna Rossi to database
=> Add Squirted

Contents/Code/PAdatabaseActors.py
=> Added Dania Vega to TS

Contents/Code/siteSpizoo.py
Fix xPath for actorLink for Mr Lucky POV
=> Fix actorLink for Mr Lucky POV

Contents/Code/siteData18Movies.py
Fix Actors and Image Grabbing
Actors will stop when an invalid entry is found.
=> Data18 Movies Fix

Contents/Code/PAsiteList.py, Contents/Code/networkAbbyWinters.py
Google Search was failing so I added a model page search
=> Add Model Search Fallback for Abby Winters

Contents/Code/sitePorndoePremium.py
Fixes summary, tagline and posters for PorndoePremium sites.
=> PorndoePremium fixes

Contents/Code/networkKink.py
Fixes https://github.com/PAhelper/PhoenixAdult.bundle/issues/1596
=> Kink fixes

Contents/Code/siteClubSweethearts.py
=> Fix Club Sweethearts

Contents/Code/PAsiteList.py, Contents/Code/networkBlurredMedia.py, docs/sitelist.md
=> Add Blurred Media sites

Contents/Code/PAutils.py, Contents/Code/siteData18Movies.py, Contents/Code/siteData18Scenes.py
Got IP Banned today because of a generic search yielding 1000+ results. Good on me.
The actor images are so bad it's better to just skip them for the ones in Freeones or IAFD, etc.
=> Data18 Improvements

Contents/Code/PAsiteList.py, Contents/Code/PAutils.py, Contents/Code/__init__.py, Contents/Code/networkBang.py, Contents/Code/networkDogfart.py, Contents/Code/networkNubiles.py, Contents/DefaultPrefs.json, docs/sitelist.md
- Update Nubiles and Add Mom Lover Sites
- Add Preference to Remove Stored Images
- Fix Unicode Type Error in Bang
- Add Scene # to Dog Fart Result and Pull Date from Site
=> Various Fixes and Mom Lover Addition

Contents/Code/PAsiteList.py, Contents/Code/siteBelAmi.py, docs/sitelist.md
This adds a site provider to process metadata for content from the Bel Ami Online website.
=> Bel Ami Online Support

Contents/Code/PAsiteList.py
=> Fix BadMilfs Not Matching

Contents/Code/PAsiteList.py, Contents/Code/siteCaribbeancom.py, docs/sitelist.md
added scraper for caribbeancom
updated sitelist
=> added support for caribbeancom

Contents/Code/networkGammaEntOther.py
#1670
Login Page added Cloudflare protection.
=> Evil Angel Cloudflare Fix

Contents/Code/sitePrivate.py, docs/sitelist.md
=> Private Actor, Image, Search Date and Poster Fixes

Contents/Code/siteData18Scenes.py
=> Grab Correct Data18 Scene Images

Contents/Code/PAactors.py
=> Fix Manually Added Actors

Contents/Code/PAsiteList.py, docs/sitelist.md
- PA was not able to lookup Smashed videos
- Added entry for Smashed in searchList & siteList
=> Added entry for Smashed.xxx in searchList and siteList

Contents/Code/networkCzechVR.py
Fixed problem with correct scene actors, release date and title
=> Patch CzechVR scraper

Contents/Code/PAsiteList.py
=> Add alternates for Nubiles

Contents/Code/PAdatabaseActors.py, Contents/Code/networkBang.py
Minor site change
Fixes
#1728
#1721
=> Bang! Fix Getting Wrong Json Data

Contents/Code/PAsiteList.py, README.md, docs/sitelist.md
=> Move XEmpire to GammaEntOther

Contents/Code/PAsiteList.py, Contents/Code/networkStrike3.py, Contents/Code/sitePlumperPass.py, docs/sitelist.md
=> Remove Broken Internal Search for Plumper Pass

Contents/Code/PAdatabaseActors.py, Contents/Code/sitePorndoePremium.py
Looks like there was a site change recently, updated XPath queries.
=> Fix PorndoePremium 

Contents/Code/PAdatabaseActors.py, Contents/Code/PAsiteList.py, Contents/Code/siteJacquieEtMichel.py
Change xpath and urls for JacquieEtMichelTV site change.
They started to add the actor name in the same list as genre tags. I couldn't find a good way to pick out the actors so all tags are being treated as genres.
=> Fix JacquieEtMichel

Contents/Code/siteData18Movies.py, Contents/Code/siteData18Scenes.py
=> Data18 site change

Contents/Code/siteVirtualTaboo.py
update description, poster, and tags selectors
=> patch virtual taboo

Contents/Code/networkTeenCoreClub.py
- Add Scene ID to Search
- Use Actor Name as Title when Title is a Slug (BIC_####)
- Fix Date Parsing
=> Teen Core Club Fixes and Modifications

Contents/Code/siteManyvids.py
=> Fix Search for ManyVids

Contents/Code/networkBadoinkVR.py, Contents/Code/networkThickCash.py, Contents/Code/networkThickCashOther.py, Contents/Code/siteAnalVids.py, Contents/Code/siteJulesJordan.py
Thick Cash - Fix Bug in Tagline
Thick Cash Other - Add Google Search and Direct URL Support
BadoinkVR - Prefer posters and fallback to art if none found.
Jules Jordan - Change tagline to DVD name, so it's not the studio name.
=> Thick Cash, BadoinkVR and Jules Jordan Changes

Contents/Code/siteClips4Sale.py
=> Clips4Sale/Fix Search and Update XPaths

Contents/Code/PAsearchSites.py, Contents/Code/network5Kporn.py, Contents/Code/siteSexMex.py, Contents/Code/siteXevUnleashed.py
SexMex: Fixes #1853
5KPorn: Fix Image Request
XevUnleashed: Remove Apostrophes from DirectURL
=> BugFixes/SexMex, 5KPorn and XevUnleashed

Contents/Code/siteJAVDatabase.py
=> JAVDatabase/Update JAV DB xPaths

Contents/Code/networkPKJMedia.py
- add proper score to search
- add the studio tag
- move site name to tagline
- add support for multiple actors
- other small formatting tweaks
=> Update PKJ Media: Multiple Actors / Studio Tag / Formatting

Contents/Code/networkCzechAV.py
=> CzechAV/Update Title xPaths

Contents/Code/networkKink.py
=> Kink/Fix and Update Kink Scraper

Contents/Code/PAdatabaseActors.py, Contents/Code/PAsiteList.py, Contents/Code/networkKink.py, Contents/Code/networkRomero.py, docs/sitelist.md
=> Various/Add New Romero Sites, Fix Kink SceneID Search and Fix Actor from AE

Contents/Code/siteManyvids.py
=> ManyVids/Update ManyVids Video Info URL

Contents/Code/siteManyvids.py
=> ManyVids/Check if Description is Present

Contents/Code/networkPKJMedia.py
- neglected to save file previously
=> Update networkPKJMedia.py: Summary / genresDB

Contents/Code/siteManyvids.py
=> ManyVids/Fix Search Results

Contents/Code/networkHighTechVR.py, docs/sitelist.md
=> BugFix/Use Search Title instead of File Name

Contents/Code/PAsiteList.py, docs/sitelist.md
Added
- Touch My Wife
- Taboo Heat
- B Skow
=> GammaEntOther/Add Additional Sites

Contents/Code/PAutils.py, Contents/Code/__init__.py, Contents/Code/networkGASM.py, Contents/Code/sitePrivate.py, Contents/Code/siteSpizoo.py
**Spizoo:**
- Get Images for Mr. Lucky POV
**Private:**
- Fix Collections and Remove Timestamp from Images
**GASM:**
- Replace Apostrophes in Summary and add Period to Vol in Titles
**Utils:**
- Add a Function Timer for Testing Execution Speed (useful for finding slowness in scrapers)
- Not adding any specific usages since its only necessary for testing
=> BugFix/Fixes for Spizoo, GASM and Private

Contents/Code/PAsiteList.py, Contents/Code/siteMyDirtyHobby.py
=> MyDirtyHobby/Adjust Scraper for Site Changes

Contents/Code/siteSpizoo.py
Fixes First Class POV and other Spizoo sites for #1945
=> Spizoo/Update Spizoo Search xPath

Contents/Code/networkAdultPrime.py
Fix Title for Adult Prime #1945
=> AdultPrime/Update xPath for Title

Contents/Code/siteWatch4Beauty.py
=> Watch4Beauty/Update Site Urls

Contents/Code/PAsiteList.py, docs/sitelist.md
Move LetDoeIt sites to N1S, the rest still appear to work on old scraper.
Last site needed to fix #1945
=> Porndoe/Move LetsDoeIt to N1S

Contents/Code/siteXart.py
=> BugFix/Fix X-Art Scraper Issues

Contents/Code/PAutils.py, Contents/Code/networkBang.py, Contents/Code/networkScoreGroup.py
ScoreGroup/Use Search to Match Deleted Links and Fix Summary
Bang/Include Results for Videos in Search
BugFix/Update Title Parser
- Fix Titles that start with the Letter A and Symbol
- Adjust how Initials are Handled
=> Various/Improve Matches for ScoreGroup and Bang!

Contents/Code/PAactors.py, Contents/Code/networkScoreGroup.py
Used kwargs for compatibility on other scrapers
=> MaleActorFilter/Support Getting Gender from Site Scrapers

Contents/Code/PAsiteList.py, Contents/Code/siteXConfessions.py, docs/sitelist.md, postprocessing2/PAsearchSites.py
Lust cinema uses the same api as XConfessions
=> feat: add LustCinema

Contents/Code/networkMYLF.py, Contents/Code/networkTeamSkeet.py
=> BugFix/Fix Actors on TeamSkeet and MYLF

Contents/Code/networkMYLF.py, Contents/Code/networkTeamSkeet.py
Fixes #1976 #1974 permanently, I hope. Whatever change was made was reverted overnight.
=> BugFix/Fix TeamSkeet Actors

Contents/Code/siteNaughtyAmerica.py
=> BugFix/Fix Naughty America Search and Actor Images

Contents/Code/PAsiteList.py, Contents/Code/siteMissaX.py, docs/sitelist.md
Fixes #1978
Also removed AmateurBoxxx because it now redirects to Clips4Sale and there is already a C4S scraper.
=> BugFix/Fix MissaX Search

Contents/Code/siteSexLikeReal.py
=> Fix sexlikereal

Contents/Code/networkCzechVR.py
fixed scraper for czech vr network
=> Patch czech vr

Contents/Code/PAsiteList.py, Contents/Code/networkCzechVR.py, Contents/Code/networkPornPros.py, Contents/Code/siteJAVDatabase.py, Contents/Code/siteSexLikeReal.py, Contents/Code/siteVirtualReal.py
- added czechar
- fixed czechvr
- fixed wetvr
- fixed javdatabase
- fixed SLR
- fixed virtualrealporn
=> fix multiple sites

Contents/Code/PAactors.py, Contents/Code/siteAdultEmpire.py
=> AdultEmpire/Add Age Verification

Contents/Code/siteData18Movies.py
=> Data18Movies/Fix Front Cover not Being Pulled

Contents/Code/siteMissaX.py
=> SheSeducedMe/Fix xPaths and Art

Contents/Code/networkMYLF.py, Contents/Code/networkNubiles.py, Contents/Code/networkTeamSkeet.py
=> Various Sites/Add Age Verification Cookies

Contents/Code/networkNubiles.py
=> Nubiles/Fix Search Issue

Contents/Code/PAsiteList.py, docs/sitelist.md
=> LethalHardcore/Move Site to Gamma

Contents/Code/PAsiteList.py, postprocessing2/PAsearchSites.py
Added Reality Sis @ `siteNum = 1040`
grouping with other 'Nubiles' would require lots of renumbering.
=> add Reality Sis

Contents/Code/PAsiteList.py, docs/sitelist.md
Strike3 Network/Vixen Media Group launched a new website wifey.com
Added entries to sitelist for that.
=> Added Wifey.com by Strike3 Network to Sitelist

Contents/Code/networkPKJMedia.py
update xpaths for site changes
=> Fix PKJMedia Network

Contents/Code/siteData18Movies.py, Contents/Code/siteData18Scenes.py, Contents/Libraries/Shared/googlesearch/__init__.py, Contents/Libraries/Shared/googlesearch/user_agents.py
Fixes #2015 since google search will no longer respond with no results
Also while I'm here fixed the blank subsite in Data 18 search results
=> fix(googlesearch): Update the Google Search Scraper
